name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ å½“å‰å·¥ä½œæµå‡ºå‘äº‹ä»¶åç§°${{ github.event_name }} ."
      - run: echo "ğŸ§ å½“å‰å·¥ä½œæµè¿è¡Œçš„æ“ä½œç³»ç»Ÿ ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” å·¥ä½œæµè¿è¡Œçš„ä»“åº“åˆ†æ”¯ ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ å½“å‰ä»“åº“ä»£ç cloneçŠ¶æ€ ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ å·¥ä½œæµç°åœ¨å¯ä»¥åœ¨è¿è¡Œå™¨ä¸Šæµ‹è¯•æ‚¨çš„ä»£ç äº†ã€‚"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ å·¥ä½œæµjobså·¥ä½œçŠ¶æ€ ${{ job.status }}."
